---
- name: Configure Minecraft Server
  hosts: localhost
  gather_facts: false

  vars:
    minecraft_image: "itzg/minecraft-server"

  tasks:
    # Install kubectl and configure kubeconfig
    - name: Install kubectl
      become: true
      apt:
        name: kubectl
        update_cache: true

    - name: Create kubectl configuration
      become: true
      template:
        src: kubectl.cfg.j2
        dest: /home/ubuntu/.kube/config
        mode: "0644"

    # Configure Minecraft Deployment
    - name: Create Minecraft Deployment
      become: true
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: minecraft
            labels:
              app: minecraft
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: minecraft
            template:
              metadata:
                labels:
                  app: minecraft
              spec:
                containers:
                  - name: minecraft
                    image: "{{ minecraft_image }}"
                    ports:
                      - containerPort: 25565
                    env:
                      - name: EULA
                        value: "true"
            apiVersion: apps/v1

    # Configure Minecraft Service
    - name: Create Minecraft Service
      become: true
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: minecraft-service
          spec:
            selector:
              app: minecraft
            ports:
              - name: minecraft
                port: 25565
                targetPort: 25565
            type: LoadBalancer
